<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEventAgenda(){
        $now = new \DateTime(date("Y-m-d")." 00:00:00");
        $qb = $this->_em->createQueryBuilder()
            ->addSelect('e.date,e.note')
            ->from("AppBundle:Event", 'e')
            ->where("e.date > :now")
            ->setParameter('now',$now);
        $eventAgenda = $qb->getQuery()->getArrayResult();
        for($i=0;$i<count($eventAgenda);$i++){
            $eventAgenda[$i]['type'] = "Event";
        }
        return $eventAgenda;
    }

    public function getFiltredEventAgenda($startDate,$endDate){
        $qb = $this->_em->createQueryBuilder()
            ->addSelect('e.date,e.note')
            ->from("AppBundle:Event", 'e')
            ->where("e.date >= :startDate")
            ->andWhere("e.date <= :endDate")
            ->setParameter('startDate',$startDate)
            ->setParameter('endDate',$endDate);
        $eventAgenda = $qb->getQuery()->getArrayResult();
        for($i=0;$i<count($eventAgenda);$i++){
            $eventAgenda[$i]['type'] = "Event";
        }
        return $eventAgenda;
    }
}
